//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaDeMotos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSMOTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATOSMOTOS()
        {
            this.MOTO = new HashSet<MOTO>();
            this.MOTO1 = new HashSet<MOTO>();
        }
    
        public int ID_DATOSM { get; set; }
        public Nullable<int> MOTOR { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> AÑO { get; set; }
        public string TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOTO> MOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOTO> MOTO1 { get; set; }
    }
}
