//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaDeMotos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_VENTA { get; set; }
        public Nullable<int> ID_PROVEDOR { get; set; }
        public Nullable<int> FACTURA_ID { get; set; }
    
        public virtual PROVEDORES PROVEDORES { get; set; }
        public virtual PROVEDORES PROVEDORES1 { get; set; }
    }
}
