//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTOS
    {
        public int ID { get; set; }
        public string MARCA { get; set; }
        public int MOTOR { get; set; }
        public int MODELO { get; set; }
        public int AÑO { get; set; }
        public int N_FABRICA { get; set; }
    }
}
